### PR TITLE
upgrade go version to 1.17 for webhook-example

### PR DESCRIPTION
**Pull request by roytev**
Signed-off-by: Roi Teveth <roytev@gmail.com>

### CODE REVIEW

**Comment by roytev** [comment]
Hi @munnerz i created a PR here to upgrade the go version for https://github.com/cert-manager/webhook-example/pull/36

**Comment by munnerz** [comment]
Thanks!

/lgtm
/approve

**Comment by roytev** [comment]
Hi @munnerz can you merge please?

**Review by wallrj — APPROVED** [review]
/lgtm

**Comment by roytev** [comment]
@wallrj can you help? its merged but not deployed

**Comment by roytev** [comment]
Thanks @wallrj

**Pull request merged**
