### PR TITLE
Add boilersuite presubmits

### PR DESCRIPTION
**Pull request by SgtCoDFish**

### CODE REVIEW

**Review by irbekrm — DISMISSED** [review]
Thanks Ashley

I guess we might also want to add the repo to label sync https://github.com/jetstack/testing/blob/master/prow/cluster/labelsync_cronjob.yaml#L36

I do not remember right now which labels it adds that we don't get by default.. so add it if you want to, happy for this to merge either way

/lgtm
/hold

**Comment by SgtCoDFish** [comment]
Thanks, I've added labelsync as well :grin: I wouldn't be surprised if I missed something else tbh!

/unhold

**Comment by irbekrm** [comment]
> Thanks, I've added labelsync as well grin I wouldn't be surprised if I missed something else tbh!

We should probably document how to onboard a repo

/lgtm

**Comment by irbekrm** [comment]
We need to reapply the Prow yamls btw for the label sync update to take place, idk if you were planning to do it @SgtCoDFish

**Comment by SgtCoDFish** [comment]
I can, but it'd probably take me a moment or two to figure out and be confident about it. If you could do it quickly that'd be massively helpful, but if you don't have the bandwidth that's totally fine and I'll figure it out :grin:

**Comment by irbekrm** [comment]
I've applied it and presumably it did something
```
irbe@prow$ k logs manual-label-sync-wxk6v | grep boiler
{"component":"label_sync","file":"k8s.io/test-infra/label_sync/main.go:417","func":"main.loadLabels.func1","level":"info","msg":"Listing labels for repo","org":"cert-manager","repo":"boilersuite","severity":"info","time":"2023-04-27T10:34:27Z"}
{"client":"github","component":"label_sync","file":"k8s.io/test-infra/prow/github/client.go:918","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"GetRepoLabels(cert-manager, boilersuite)","severity":"info","time":"2023-04-27T10:34:27Z"}
{"color":"e11d21","component":"label_sync","file":"k8s.io/test-infra/label_sync/main.go:471","func":"main.change","label":"kind/bug","level":"info","msg":"change","repo":"boilersuite","severity":"info","time":"2023-04-27T10:34:27Z"}
{"component":"label_sync","file":"k8s.io/test-infra/label_sync/main.go:624","func":"main.RepoUpdates.DoUpdates","level":"info","msg":"Applying 1 changes","org":"cert-manager","repo":"boilersuite","severity":"info","time":"2023-04-27T10:34:27Z"}
{"client":"github","component":"label_sync","file":"k8s.io/test-infra/prow/github/client.go:918","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"UpdateRepoLabel(cert-manager, boilersuite, kind/bug, kind/bug, e11d21)","severity":"info","time":"2023-04-27T10:34:27Z"}
```

It really is just `kubectl apply -f ./prow/cluster` these days, thanks to Tim's efforts

**Pull request merged**
