### PR TITLE
Apply changes from https://github.com/cert-manager/release/pull/114

### PR DESCRIPTION
**Pull request by SgtCoDFish**
Should be merged after https://github.com/cert-manager/release/pull/114

### CODE REVIEW

**Review by irbekrm — CHANGES_REQUESTED** [review]
Thank you @SgtCoDFish 

I think we also want to update the required tests for master in this PR https://github.com/jetstack/testing/blob/master/config/config.yaml#L61-L62 apart from that all makes sense to me 👍🏼

**Comment by SgtCoDFish** [comment]
> I think we also want to update the required tests for master in this PR https://github.com/jetstack/testing/blob/master/config/config.yaml#L61-L62 apart from that all makes sense to me 👍🏼

Ah you always spot useful stuff in your reviews! Of course we do, thank you!

**Comment by SgtCoDFish** [comment]
I've pushed an update for the required tests. I think I should add an automated test to check for this [here](https://github.com/jetstack/testing/blob/master/config/jobs/testing/testing-presubmits.yaml) but I'll bite that off another time!

**Review by irbekrm — APPROVED** [review]
> I think I should add an automated test to check for this [here](https://github.com/jetstack/testing/blob/master/config/jobs/testing/testing-presubmits.yaml) but I'll bite that off another time!

Agree 👍🏼 

thanks for the update!

/lgtm

**Pull request merged**
