### PR TITLE
Add some missing and updated commands for the katacoda-lint image

### PR DESCRIPTION
**Pull request by wallrj**
Part of: https://github.com/jetstack/katacoda-scenarios/issues/40

### CODE REVIEW

**Comment by munnerz** [comment]
Let's wait for CI to come back on this, then we can merge and I'll build/push a new image :smile:

**Comment by munnerz** [comment]
Have you managed to test this locally and get it running/passing?

**Comment by wallrj** [comment]
Yep, I built the image and ran it with this branch: https://github.com/jetstack/katacoda-scenarios/pull/41

**Comment by wallrj** [comment]
@munnerz I added the Katacoda CLI to  the Dockerfile  which requires a glibc container, so I switched to a Debian base image.
Tested locally with https://github.com/jetstack/katacoda-scenarios/pull/47

Will you build and push the image?

**Comment by munnerz** [comment]
Image built and pushed as `eu.gcr.io/jetstack-build-infra-images/katacoda-lint:v20180920-7128798`

If you can PR against the `config/` directory to bump the appropriate job, to this image :smile:

**Pull request merged**
