### PR TITLE
Update upgrade test to reference new target

### PR DESCRIPTION
**Pull request by SgtCoDFish**
This should remove the last traces of bazel in our presubmits!

### CODE REVIEW

**Comment by irbekrm** [comment]
Thank you very much for working on this @SgtCoDFish !

Should we make the same change [in the periodic](https://github.com/jetstack/testing/blob/master/config/jobs/cert-manager/cert-manager/cert-manager-periodics.yaml#L329-L330)? Apart from that happy to lgtm

**Comment by SgtCoDFish** [comment]
Good suggestion, thanks @irbekrm  - not sure how I missed that.

I've added a second commit which does that and also which reduces the resource requirements which seemed high. Does that look reasonable? :grin:

**Comment by irbekrm** [comment]
Thanks @SgtCoDFish !

For the resource requirements, I would slightly prefer if we re-evaluated what proportion of node resources each test type needs + whether we could, for example benefit from a different node size (as there probably have been some changes in that now that we use make) + monitor for possible flakes in one single PR so that all the reasoning etc is in one place.
At the moment the resource requiremement for each job that spins up kind cluster is ~50% of a node so that no more than 2 such jobs get allocated to that node.

Adding a hold if you agree else happy for it to go in as is

/hold
/lgtm
/approve

**Comment by SgtCoDFish** [comment]
@irbekrm I've reverted the resource changes - I agree that it's probably better to attack them all in one go, yeah.

**Comment by irbekrm** [comment]
Thanks @SgtCoDFish and thanks for working on this!

/hold cancel
/lgtm

**Pull request merged**
